#!/usr/bin/env python3
"""
Packages gdresources* raw assets and the user-data generated by running the
extraction pipeline on them, then publishes both to a GitHub release.

The resulting release powers the light deployment flow:
  - gdresources-light.zip(.001...)  raw light resources (dev opt-in fetch:
    `python scripts/download_user_data.py --asset gdresources`)
  - user-data.zip(.001...)          pipeline output built from those resources,
    fetched by the Docker build / entrypoint for deployed containers.

Publishing uses the GitHub CLI (`gh`), which must be installed and
authenticated (`gh auth login` or GH_TOKEN).

Usage:
    python scripts/create_gdresources_release.py \
        --gdresources-dir local-input/gdresources-light \
        --tag gdresources-light-2026.09.17
"""

import argparse
import os
import shutil
import subprocess
import sys
import time
import zipfile

# Keep parts under GitHub's 2 GB asset limit with headroom (same as pack_and_split).
CHUNK_SIZE = 1500 * 1024 * 1024

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pack_and_split_user_data import split_file  # noqa: E402


def create_folder_zip(source_dir, output_zip, arc_root, exclude_dirs=()):
    """Zip source_dir with entries rooted at arc_root (e.g. 'user-data/...')."""
    print(f"Counting files in '{source_dir}'...")
    all_files = []
    total_bytes = 0
    for root, dirs, files in os.walk(source_dir):
        dirs[:] = [d for d in dirs if d not in exclude_dirs]
        for f in files:
            fp = os.path.join(root, f)
            all_files.append(fp)
            total_bytes += os.path.getsize(fp)

    print(f"Found {len(all_files)} files ({total_bytes / (1024**3):.2f} GB uncompressed).")
    print(f"Archiving into '{output_zip}' (root: {arc_root}/) ...")

    start_time = time.time()
    last_print = start_time
    written_bytes = 0

    with zipfile.ZipFile(output_zip, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6, allowZip64=True) as zf:
        for idx, fp in enumerate(all_files, start=1):
            rel = os.path.relpath(fp, start=source_dir).replace("\\", "/")
            zf.write(fp, arcname=f"{arc_root}/{rel}")
            written_bytes += os.path.getsize(fp)

            now = time.time()
            if now - last_print >= 3.0 or idx == len(all_files):
                pct = (written_bytes / total_bytes) * 100 if total_bytes > 0 else 100
                elapsed = now - start_time
                print(f"  Archiving: {idx}/{len(all_files)} files ({pct:.1f}%) in {elapsed:.0f}s...", flush=True)
                last_print = now

    zip_size = os.path.getsize(output_zip)
    print(f"Created '{output_zip}' ({zip_size / (1024**2):.1f} MB) in {time.time() - start_time:.1f}s.")
    return output_zip


def package_folder(source_dir, output_zip, exclude_dirs=()):
    """Zip a folder as <name>.zip and split it if it exceeds the chunk size.

    Returns the list of files to upload (the single zip or its split parts).
    """
    if not os.path.isdir(source_dir):
        raise FileNotFoundError(f"Source directory '{source_dir}' does not exist.")

    arc_root = os.path.basename(os.path.normpath(source_dir))
    create_folder_zip(source_dir, output_zip, arc_root, exclude_dirs=exclude_dirs)

    if os.path.getsize(output_zip) <= CHUNK_SIZE:
        return [output_zip]

    print(f"'{output_zip}' exceeds the {CHUNK_SIZE / (1024**3):.1f} GB GitHub asset limit, splitting...")
    parts_dir = os.path.dirname(os.path.abspath(output_zip))
    parts = split_file(output_zip, parts_dir, CHUNK_SIZE)
    os.remove(output_zip)
    print(f"Removed intermediate '{output_zip}' (parts are self-sufficient).")
    return parts


def create_release(repo, tag, title, notes, files):
    """Create (or upload to) a GitHub release via the gh CLI."""
    gh = shutil.which("gh")
    if not gh:
        print("Error: 'gh' CLI not found on PATH. Install it from https://cli.github.com/", file=sys.stderr)
        return False

    cmd = [gh, "release", "create", tag, "--repo", repo, "--title", title, "--notes", notes]
    cmd.extend(files)
    print("Running:", " ".join(cmd[:8]), "...")

    result = subprocess.run(cmd)
    if result.returncode != 0:
        print(f"Error: gh release create failed with exit code {result.returncode}.", file=sys.stderr)
        return False

    print(f"Release '{tag}' published with {len(files)} asset file(s).")
    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Package gdresources + user-data and publish a GitHub release")
    parser.add_argument("--gdresources-dir", default="local-input/gdresources-light",
                        help="gdresources* folder to package (default: local-input/gdresources-light)")
    parser.add_argument("--user-data-dir", default="user-data",
                        help="Pipeline-generated user-data folder to package (default: user-data)")
    parser.add_argument("--repo", default=os.environ.get("GITHUB_REPO", "Guigeekun/Terra-Tools"),
                        help="GitHub repository (default: GITHUB_REPO env or Guigeekun/Terra-Tools)")
    parser.add_argument("--tag", required=True, help="Release tag (e.g. gdresources-light-2026.09.17)")
    parser.add_argument("--title", default=None, help="Release title (defaults to the tag)")
    parser.add_argument("--notes", default="gdresources (light) raw assets and the user-data generated "
                                           "from them by the Terra-Tools extraction pipeline.",
                        help="Release notes")
    parser.add_argument("--keep-archives", action="store_true",
                        help="Keep the generated zip parts in the project root after publishing")

    args = parser.parse_args()

    print(f"Packaging '{args.gdresources_dir}' and '{args.user_data_dir}' for release '{args.tag}'...")
    upload_files = []
    upload_files += package_folder(args.gdresources_dir, f"{os.path.basename(os.path.normpath(args.gdresources_dir))}.zip")
    # .download_cache is transient state from previous release downloads.
    upload_files += package_folder(args.user_data_dir, "user-data.zip", exclude_dirs=(".download_cache",))

    print("Files to upload:")
    for f in upload_files:
        print(f"  - {f} ({os.path.getsize(f) / (1024**2):.1f} MB)")

    ok = create_release(args.repo, args.tag, args.title or args.tag, args.notes, upload_files)

    if ok and not args.keep_archives:
        print("Cleaning up local archives...")
        for f in upload_files:
            os.remove(f)

    sys.exit(0 if ok else 1)
