"""Export the Enemies enum (enemy_id -> global-metadata symbol) to backend/enemy_enum.py.

Run from the repo root after adding new game versions:
    python scripts/export_enemy_enum.py

The APK path matches decompile_and_parse_all.py. The generated module is committed
so the backend can derive enemy families (ML_, PUDDING_, MONEY_, ...) at serve time
without shipping the APK.
"""
import zipfile
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
APK_PATH = BASE_DIR / "local-input" / "terra-battle-5.5.7-170.apk"
OUTPUT_PATH = BASE_DIR / "backend" / "enemy_enum.py"

HEADER = '''"""GENERATED by scripts/export_enemy_enum.py — do not edit by hand.

Maps enemy_id (1-based, matching EnemyData.json IDs) to its symbol in the
Enemies enum extracted from global-metadata.dat inside the APK. Symbols encode
spawn families (ML_ = Metal Zone, PUDDING_/TIN_/MONEY_/PUPPET_ = event enemies,
SP<chapter>_ = chapter-specific event spawns, CH<chapter>_ = story spawns).
"""

ENEMY_ENUM_SYMBOLS = {
'''


def main():
    with zipfile.ZipFile(APK_PATH) as archive:
        metadata = archive.read("assets/bin/Data/Managed/Metadata/global-metadata.dat")

    idx = metadata.find(b"CH1_BAKUROU")
    if idx == -1:
        raise SystemExit("CH1_BAKUROU not found in metadata")
    names = []
    for part in metadata[idx:].split(b"\x00"):
        name = part.decode(errors="replace").strip()
        if not name:
            continue
        if name == "NumberOfEnemies":
            break
        names.append(name)

    lines = "".join(f'    {i + 1}: "{name}",\n' for i, name in enumerate(names))
    OUTPUT_PATH.write_text(f"{HEADER}{lines}}}\n", encoding="utf-8", newline="\n")
    print(f"Wrote {len(names)} enum symbols to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
