"""Extract runtime-configured enemy drops from the native chapter classes.

Event chapters (Eidolon quests, hunts, crossover descends) configure their
boss drops at spawn time from compiled code instead of the EnemyData drop
tables: each ChapterXXX class in libil2cpp.so boxes an item id and calls
SetItemDropRatio(entity, itemIdx, dropRatio) inside its Init_<enemy> spawner
methods. That data is invisible to EnemyData.json, so items dropped this way
showed no "Where to Obtain" sources.

This script disassembles the Init_* methods of every ChapterXXX class
(method RVAs taken from user-data/dump.cs, binary from the APK in
local-input/) with llvm-objdump and recovers the (item, ratio) pairs from
the instruction pattern:

    mov  w8, #0x3b              ; item id (The Emperor = 59)
    str  w8, [x22, #0x20]       ; stored into the boxed ItemCode
    mov  w2, wzr                ; itemIdx
    orr  w3, wzr, #0x1e         ; dropRatio = 30 (%)
    ldr  x9, [x8, #0x7e0]
    blr  x9                     ; SetItemDropRatio(entity, 0, 30, item 59)

A drop slot can carry several item alternatives (adjacent int[] stores at
#0x20/#0x24/...), so the recovered per-item chance is slot_ratio / slot_size
(matching the rates documented on the community wiki).

Not every boss drop is configured this way: a few chapters (Cryptid Forest,
the Little Noah crossovers, ...) register their loot in chapter-level
SetDrop-style registry functions whose per-chapter attribution would need a
deeper analysis of the container structures. Those stages stay unattributed
until the extractor learns that pattern.

The recovered configs are attributed to stages by joining the Init_<var>
method suffix with the enemy_var already recorded in StagesLayout.json
(pipeline-generated by extract_native_stages.py / decompile_and_parse_all.py).
Layout section keys are battle-sequence indices, not quest sections: the
r-th distinct battle index of a chapter belongs to the r-th quest section
(clamped), which StageDrops.json records as "section" (keeping the raw
"battle_index" for reference).

Output: user-data/extracted-gamedata/game_data/StageDrops.json
    { chapter_no: { section: [ {enemy_var, enemy_id, item_id, item_idx, ratio} ] } }

Usage:
    py -3 scripts/extract_native_drops.py
"""

import json
import re
import subprocess
import sys
import zipfile
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
APK_PATH = BASE_DIR / "local-input" / "terra-battle-5.5.7-170.apk"
DUMP_CS_PATH = BASE_DIR / "user-data" / "dump.cs"
LIB_PATH = BASE_DIR / "user-data" / "libil2cpp.so"
STAGES_LAYOUT_PATH = BASE_DIR / "user-data" / "extracted-gamedata" / "game_data" / "StagesLayout.json"
OUTPUT_PATH = BASE_DIR / "user-data" / "extracted-gamedata" / "game_data" / "StageDrops.json"

OBJDUMP_CMD = "llvm-objdump"

# Instruction fingerprint bounds.
MAX_ITEMS = 200        # ItemSet has ~181 entries; item ids are small ints
MAX_RATIO = 100        # dropRatio is a percentage
LOOKAHEAD = 24         # instructions between the first box store and the call
VCALL_SLOT_OFFSET = "#0x7e0"   # ChapterBase vtable slot of SetItemDropRatio
BOX_OFFSETS = ("#0x20", "#0x24", "#0x28", "#0x2c")  # int[] item slots

INSN_RE = re.compile(r"^\s*([0-9a-f]+):\s+[0-9a-f]+\s+([.\w]+)\s*(.*?)\s*$", re.I)
CLASS_DECL_RE = re.compile(r"^(?:public|private|internal|protected)?\s*(?:sealed\s+|static\s+|abstract\s+)*class\s+(Chapter\d+)\s*(?::.*)?\s*// TypeDefIndex")
RVA_RE = re.compile(r"// RVA: 0x([0-9A-Fa-f]+)")
METHOD_RE = re.compile(r"(?:public|private|protected|internal).*?\s(\S+)\((.*?)\)\s*\{ \}$")


def parse_dump_cs():
    """Extract the Enemies enum and per-chapter Init_* method RVAs from dump.cs."""
    enemies = {}
    chapter_methods = {}  # "Chapter4000" -> list of (method_name, rva)
    inside_enemies = False
    current_class = None
    pending_rva = None

    with open(DUMP_CS_PATH, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            if not inside_enemies:
                if "enum Enemies" in line:
                    inside_enemies = True
                    continue
            else:
                if line.startswith("}"):
                    inside_enemies = False
                else:
                    m = re.search(r"Enemies\s+(\w+)\s*=\s*(-?\d+)\s*;", line)
                    if m:
                        enemies[m.group(1)] = int(m.group(2))
                    continue

            class_match = CLASS_DECL_RE.match(line.strip())
            if class_match:
                current_class = class_match.group(1)
                chapter_methods.setdefault(current_class, [])
                pending_rva = None
                continue

            if current_class is None:
                continue

            if line.strip().startswith("}"):  # class body ended
                current_class = None
                pending_rva = None
                continue

            rva_match = RVA_RE.search(line)
            if rva_match:
                pending_rva = int(rva_match.group(1), 16)
                continue

            if pending_rva is not None:
                method_match = METHOD_RE.search(line.strip())
                if method_match:
                    name, params = method_match.group(1), method_match.group(2)
                    if name.startswith("Init_") and params != "":
                        chapter_methods[current_class].append((name, pending_rva))
                pending_rva = None

    return enemies, chapter_methods


def ensure_libil2cpp():
    if LIB_PATH.exists():
        return
    if not APK_PATH.exists():
        print(f"Error: neither {LIB_PATH} nor {APK_PATH} exists.")
        sys.exit(1)
    print(f"Extracting libil2cpp.so from {APK_PATH.name}...")
    LIB_PATH.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(APK_PATH) as z:
        with z.open("lib/arm64-v8a/libil2cpp.so") as src, open(LIB_PATH, "wb") as dest:
            dest.write(src.read())


def parse_insn(operands):
    """Return the operand string with objdump's '// =N' comments stripped."""
    return operands.split("//", 1)[0].replace(" ", "")


def extract_method_drops(start_rva, stop_rva):
    """Disassemble one method and pull out (item_id, item_idx, ratio) tuples.

    SetItemDropRatio(entity, itemIdx, dropRatio, int[] items) is reached
    through the ChapterBase vtable slot (ldr x9, [x8, #0x7e0]; blr x9). The
    item arguments are stored into a small int[] box right before the call
    (str wN, [xM, #0x20] .. #0x2c); itemIdx and dropRatio are passed in w2
    and w3. A drop slot may carry several item alternatives.
    """
    cmd = [OBJDUMP_CMD, "--disassemble",
           f"--start-address={start_rva}", f"--stop-address={stop_rva}",
           str(LIB_PATH)]
    try:
        res = subprocess.run(cmd, capture_output=True, text=True, check=True)
    except (subprocess.CalledProcessError, OSError) as e:
        print(f"  objdump failed for {hex(start_rva)}: {e}")
        return []

    regs = {}             # w-register -> immediate constant
    pending = None        # {'items': [...], 'age': n, 'vcall': bool}
    drops = []

    def emit(pending, regs):
        idx = regs.get("w2")
        ratio = regs.get("w3")
        if ratio is None or not (0 <= ratio <= MAX_RATIO):
            return
        items = [i for i in pending["items"] if 1 <= i <= MAX_ITEMS]
        if not items:
            return
        # A slot rolls `ratio` and yields one of its items uniformly, so the
        # effective per-item chance is ratio / len(items) (matches observed
        # rates documented on the community wiki).
        per_item = ratio // len(items)
        for item in items:
            drops.append({
                "item_id": item,
                "item_idx": idx,
                "ratio": per_item,
                "slot_ratio": ratio,
                "slot_size": len(items),
            })

    for line in res.stdout.splitlines():
        m = INSN_RE.match(line)
        if not m:
            continue
        _, mnemonic, operands = m.group(1), m.group(2).lower(), parse_insn(m.group(3))

        if mnemonic in ("mov", "orr", "movz"):
            mm = re.match(r"^w(\d+),wzr,#(0x[0-9a-f]+|\d+)$", operands)
            if mm:
                regs[f"w{mm.group(1)}"] = int(mm.group(2), 0)
                continue
            mm = re.match(r"^w(\d+),#(0x[0-9a-f]+|\d+)$", operands)
            if mm:
                regs[f"w{mm.group(1)}"] = int(mm.group(2), 0)
                continue
            mm = re.match(r"^w(\d+),wzr$", operands)
            if mm:
                regs[f"w{mm.group(1)}"] = 0
                continue

        sm = re.match(r"^w(\d+),\[x\d+,(#0x[0-9a-f]+)\]$", operands)
        if sm and mnemonic == "str" and sm.group(2) in BOX_OFFSETS:
            val = regs.get(f"w{sm.group(1)}")
            if val is not None and 1 <= val <= MAX_ITEMS:
                if pending is None:
                    pending = {"items": [], "age": 0, "vcall": False}
                if val not in pending["items"]:
                    pending["items"].append(val)
            continue

        if pending is not None:
            pending["age"] += 1
            if VCALL_SLOT_OFFSET in operands and mnemonic == "ldr":
                pending["vcall"] = True
            elif mnemonic == "blr":
                if pending["vcall"]:
                    emit(pending, regs)
                pending = None
                regs.clear()
            elif pending["age"] > LOOKAHEAD:
                pending = None

    return drops


def main():
    if not DUMP_CS_PATH.exists():
        print(f"Error: dump.cs not found at {DUMP_CS_PATH}")
        sys.exit(1)
    ensure_libil2cpp()

    enemies, chapter_methods = parse_dump_cs()
    total_methods = sum(len(v) for v in chapter_methods.values())
    print(f"Loaded {len(enemies)} enemy enum names and {len(chapter_methods)} "
          f"chapter classes ({total_methods} Init_* methods) from dump.cs")

    # Pass A: drop configs per (chapter, Init suffix)
    suffix_drops = {}  # (chapter_no, "MS_Artemis") -> [drop dicts]
    for chap_name, methods in sorted(chapter_methods.items()):
        chapter_no = int(re.match(r"Chapter(\d+)", chap_name).group(1))
        rvas = sorted(rva for _, rva in methods)
        rva_successors = {rvas[i]: rvas[i + 1] for i in range(len(rvas) - 1)}
        for name, rva in methods:
            stop = rva_successors.get(rva, rva + 0x2000)
            found = extract_method_drops(rva, stop)
            if not found:
                continue
            suffix = name[len("Init_"):]
            suffix_drops.setdefault((chapter_no, suffix), []).extend(found)

    print(f"Recovered drop configs for {len(suffix_drops)} enemy spawners.")

    # Pass B: attribute to stages via StagesLayout.json enemy_var entries.
    # In the layout, a chapter's section keys are battle-sequence indices,
    # which exceed the quest sections when a quest section runs several
    # battles (e.g. chapter 2000 hosts its four bosses at indices 1,3,5,7).
    # The r-th distinct battle index belongs to the r-th quest section,
    # clamped to the quest section count from BattleData.
    battle_data = json.loads(STAGES_LAYOUT_PATH.with_name("BattleData.json").read_text(encoding="utf-8"))
    quest_section_counts = {ch["chapterNo"]: len(ch.get("sections", [])) for ch in battle_data["chapters"]}

    layout = json.loads(STAGES_LAYOUT_PATH.read_text(encoding="utf-8"))
    battle_index_maps = {}
    for chapter_no, sections in layout.items():
        count = quest_section_counts.get(int(chapter_no))
        if not count:
            continue
        indices = sorted(int(k) for k in sections)
        battle_index_maps[chapter_no] = {idx: min(r, count) for r, idx in enumerate(indices, start=1)}

    stage_drops = {}
    matched = 0
    for chapter_no, sections in layout.items():
        index_map = battle_index_maps.get(chapter_no, {})
        for section, waves in sections.items():
            quest_section = index_map.get(int(section))
            if quest_section is None:
                continue
            for wave in waves:
                for spawn in wave.get("enemies", []):
                    var = spawn.get("enemy_var")
                    if not var:
                        continue
                    found = suffix_drops.get((int(chapter_no), var))
                    if not found:
                        continue
                    matched += 1
                    bucket = stage_drops.setdefault(str(chapter_no), {}).setdefault(str(quest_section), [])
                    for drop in found:
                        entry = {
                            "enemy_var": var,
                            "enemy_id": spawn.get("enemy_id"),
                            "item_id": drop["item_id"],
                            "item_idx": drop["item_idx"],
                            "ratio": drop["ratio"],
                            "slot_ratio": drop["slot_ratio"],
                            "slot_size": drop["slot_size"],
                            "battle_index": int(section),
                        }
                        if entry not in bucket:
                            bucket.append(entry)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(stage_drops, indent=1, ensure_ascii=False), encoding="utf-8")

    total = sum(len(v) for secs in stage_drops.values() for v in secs.values())
    print(f"Matched {matched} spawner usages across stages -> {total} stage drop entries.")
    print(f"Saved {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
